name = "Pokéblock - Cobblemon Skyblock"
author = "LucyAzalea"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8d58316d9755ac8c28114b6e5305e89b516ca0e95122ce5aa82eac0672d1cd7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"

[options]
datapack-folder = "global_packs/required_data"
