name = "Pokéblock - Cobblemon Skyblock"
author = "LucyAzalea"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8506f72dc2edd400386279b9ab0dd9849101c13ef9f427f33cd69dba720a8636"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"

[options]
datapack-folder = "global_packs/required_data"
