name = "Pokéblock - Cobblemon Skyblock"
author = "LucyAzalea"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4feb793afa1bb3006c941be15d645c93776e48e13fe80f49a02660972477190"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"

[options]
datapack-folder = "global_packs/required_data"
